---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.5:8001/eureka/

# Application Properties Here!!!
---
spring:
  banner:
    location: static/banner.txt

---
spring:
  application:
    name: sciroc-web-mvc

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
  port: 8000